/**
 * Chain interaction via polkadot-api (PAPI).
 *
 * SETUP REQUIRED: Before using, generate PAPI descriptors:
 *   1. Start the node:  cd mental-poker-runtime && ./target/release/mental-poker-node --dev
 *   2. Generate types:  cd client && npx papi add -w ws://127.0.0.1:9944 mental-poker-runtime
 *
 * This creates .papi/descriptors/ with typed chain definitions.
 */

import { createClient, type PolkadotSigner, type PolkadotClient } from "polkadot-api";
import { getWsProvider } from "polkadot-api/ws-provider/web";
// Generated by `npx papi add`. Won't resolve until codegen is done.
// @ts-expect-error -- generated by papi add
import { mentalPokerRuntime } from "@polkadot-api/descriptors";

export type TypedApi = ReturnType<PolkadotClient["getTypedApi"]>;

export interface ChainConnection {
  client: PolkadotClient;
  api: TypedApi;
}

/** Connect to the Substrate node. */
export async function connect(
  wsUrl: string = "ws://127.0.0.1:9944",
): Promise<ChainConnection> {
  const provider = getWsProvider(wsUrl);
  const client = createClient(provider);
  const api = client.getTypedApi(mentalPokerRuntime);
  return { client, api };
}

/** Disconnect from the node. */
export function disconnect(conn: ChainConnection): void {
  conn.client.destroy();
}

// --- Extrinsic Helpers ---
// Each function submits a tx and waits for it to be included in a finalized block.

export async function createGame(
  api: TypedApi,
  signer: PolkadotSigner,
  deckSize: number,
  numPlayers: number,
): Promise<number> {
  const result = await (api as any).tx.MentalPoker.create_game({
    deck_size: deckSize,
    num_players: numPlayers,
  }).signAndSubmit(signer);

  // Extract game_id from GameCreated event
  for (const event of result.events) {
    if (
      event.type === "MentalPoker" &&
      event.value.type === "GameCreated"
    ) {
      return event.value.value.game_id;
    }
  }
  // Fallback: read GameCounter - 1
  const counter = await (api as any).query.MentalPoker.GameCounter.getValue();
  return counter - 1;
}

export async function registerPlayer(
  api: TypedApi,
  signer: PolkadotSigner,
  gameId: number,
  playerHelloBytes: Uint8Array,
): Promise<void> {
  await (api as any).tx.MentalPoker.register_player({
    game_id: gameId,
    player_hello_bytes: playerHelloBytes,
  }).signAndSubmit(signer);
}

export async function submitMaskedDeck(
  api: TypedApi,
  signer: PolkadotSigner,
  gameId: number,
  maskedDeckBytes: Uint8Array,
): Promise<void> {
  await (api as any).tx.MentalPoker.submit_masked_deck({
    game_id: gameId,
    masked_deck_bytes: maskedDeckBytes,
  }).signAndSubmit(signer);
}

export async function submitShuffle(
  api: TypedApi,
  signer: PolkadotSigner,
  gameId: number,
  shuffleMsgBytes: Uint8Array,
): Promise<void> {
  await (api as any).tx.MentalPoker.submit_shuffle({
    game_id: gameId,
    shuffle_msg_bytes: shuffleMsgBytes,
  }).signAndSubmit(signer);
}

export async function submitReveal(
  api: TypedApi,
  signer: PolkadotSigner,
  gameId: number,
  cardIndex: number,
  revealMsgBytes: Uint8Array,
): Promise<void> {
  await (api as any).tx.MentalPoker.submit_reveal({
    game_id: gameId,
    card_index: cardIndex,
    reveal_msg_bytes: revealMsgBytes,
  }).signAndSubmit(signer);
}

// --- Storage Queries ---

export async function readCurrentDeck(
  api: TypedApi,
  gameId: number,
): Promise<Uint8Array> {
  const raw = await (api as any).query.MentalPoker.CurrentDeck.getValue(gameId);
  return asBytes(raw);
}

export async function readAggregateKeyData(
  api: TypedApi,
  gameId: number,
): Promise<Uint8Array> {
  const raw = await (api as any).query.MentalPoker.AggregateKeyData.getValue(gameId);
  return asBytes(raw);
}

export async function readGameInfo(
  api: TypedApi,
  gameId: number,
): Promise<{ phase: string; deck_size: number; num_players: number; registered_count: number } | undefined> {
  return (api as any).query.MentalPoker.Games.getValue(gameId);
}

export async function readShuffleIndex(
  api: TypedApi,
  gameId: number,
): Promise<number> {
  return (api as any).query.MentalPoker.ShuffleIndex.getValue(gameId);
}

/** Convert PAPI's Binary/BoundedVec<u8> to Uint8Array. */
function asBytes(val: unknown): Uint8Array {
  if (val instanceof Uint8Array) return val;
  if (val && typeof val === "object" && "asBytes" in val) {
    return (val as { asBytes(): Uint8Array }).asBytes();
  }
  if (Array.isArray(val)) return new Uint8Array(val);
  throw new Error(`Cannot convert to bytes: ${typeof val}`);
}
