/**
 * Test the mental-poker contract by submitting pre-generated payloads.
 *
 * Usage:
 *   npm run test-flow -- /path/to/test-flow.json
 *
 * The JSON file is generated by gen-test-flow and contains hex payloads
 * for each contract message: create_game, register_player1, register_player2,
 * submit_agreed_deck, reveal_card0_player1, reveal_card0_player2, query_game.
 *
 * This script submits each payload sequentially and reports results + weight.
 * Note: only player 1 (the deployer account) can submit from this script.
 * Player 2 registration and reveals would require a second funded account.
 */
import { readFileSync } from "node:fs";
import { Binary, FixedSizeBinary } from "polkadot-api";
import { loadDeployment, requireMnemonic, wsUrl } from "./env.js";
import { accountFromMnemonic } from "./signer.js";
import { connect } from "./client.js";

const jsonPath = process.argv[2];
if (!jsonPath) {
  console.error("usage: npm run test-flow -- /path/to/test-flow.json");
  process.exit(2);
}

const payloads = JSON.parse(readFileSync(jsonPath, "utf-8"));
const deployment = loadDeployment();
const account = accountFromMnemonic(requireMnemonic());
const { client, api } = await connect();

console.log(`Contract: ${deployment.contractAddress}`);
console.log(`Endpoint: ${wsUrl()}`);
console.log(`Caller:   ${account.address}`);
console.log("");

const destHex = deployment.contractAddress.startsWith("0x")
  ? deployment.contractAddress.slice(2)
  : deployment.contractAddress;
const destBytes = new Uint8Array(
  destHex.match(/.{2}/g)!.map((b: string) => parseInt(b, 16)),
);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const stringifyBig = (v: any) =>
  JSON.stringify(v, (_k, x) => (typeof x === "bigint" ? x.toString() + "n" : x), 2);

async function submitCall(name: string, hexPayload: string): Promise<boolean> {
  const clean = hexPayload.startsWith("0x") ? hexPayload.slice(2) : hexPayload;
  const input = new Uint8Array(
    clean.match(/.{2}/g)!.map((b: string) => parseInt(b, 16)),
  );

  console.log(`--- ${name} (${input.length} bytes, selector=0x${input[0]?.toString(16).padStart(2, "0")}) ---`);

  const callArgs = {
    dest: FixedSizeBinary.fromBytes(destBytes),
    value: 0n,
    weight_limit: { ref_time: 500_000_000_000n, proof_size: 5_000_000n },
    storage_deposit_limit: 10_000_000_000_000n,
    data: Binary.fromBytes(input),
  };

  try {
    const result = await api.tx.Revive.call(callArgs).signAndSubmit(account.signer);

    for (const event of result.events ?? []) {
      if (event.type === "System" && event.value?.type === "ExtrinsicSuccess") {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const w = (event.value.value as any)?.dispatch_info?.weight;
        console.log(`  OK (ref_time=${w?.ref_time}, proof_size=${w?.proof_size})`);
      } else if (event.type === "System" && event.value?.type === "ExtrinsicFailed") {
        console.log(`  FAILED: ${stringifyBig(event.value.value)}`);
      } else if (event.type === "Revive" && event.value?.type === "ContractEmitted") {
        console.log(`  ContractEmitted`);
      }
    }

    if (!result.ok) {
      console.log(`  Result: FAILED (contract reverted or trapped)`);
      return false;
    }
    console.log(`  Result: SUCCESS`);
    return true;
  } catch (e) {
    console.log(`  Error: ${e}`);
    return false;
  }
}

// Run the test flow — only steps that work with a single account
const steps: [string, string][] = [
  ["create_game", payloads.create_game],
  ["query_game", payloads.query_game],
  ["register_player1", payloads.register_player1],
  ["query_game (after register)", payloads.query_game],
];

console.log("=== Running test flow (single-account subset) ===");
console.log("Note: register_player2, submit_agreed_deck, and reveals require");
console.log("a second funded account. Testing create + register + query for now.");
console.log("");

let allOk = true;
for (const [name, payload] of steps) {
  const ok = await submitCall(name, payload);
  if (!ok) {
    allOk = false;
    console.log(`\nStopping — ${name} failed.`);
    break;
  }
  console.log("");
}

if (allOk) {
  console.log("=== All single-account steps passed ===");
  console.log("");
  console.log("To test the full flow (deck agreement + reveals), you need a");
  console.log("second account. Generate payloads with both real H160 addresses:");
  console.log("  gen-test-flow --player1 <h160-1> --player2 <h160-2>");
}

await client.destroy();
