/**
 * Submit a verify_player call to the deployed contract with a framed
 * PlayerHello + name blob generated by the `gen-hello` host tool.
 *
 *   npm run verify -- 0x<framed-hex>
 *
 * The framed blob is:
 *   u32 BE hello_len | hello_bytes | name_bytes
 *
 * We can't read the contract's 32-byte status blob from extrinsic events —
 * pallet-revive only emits ContractEmitted on explicit deposit_event calls,
 * and our contract doesn't emit any. So the signal here is:
 *   ExtrinsicSuccess → the contract ran to completion (returned, didn't trap).
 *     Status byte could be 0 (verified) or 1/2/3 (validation error).
 *   ContractTrapped / ExtrinsicFailed → panic, OOM, or invalid syscall.
 *
 * To actually read the status byte we'd need `state_call ReviveApi_call`,
 * which isn't exposed in the Passet Hub PAPI descriptors.
 */
import { Binary, FixedSizeBinary } from "polkadot-api";
import { loadDeployment, requireMnemonic, wsUrl } from "./env.js";
import { accountFromMnemonic } from "./signer.js";
import { connect } from "./client.js";

const hex = process.argv[2];
if (!hex) {
  console.error("usage: npm run verify -- 0x<framed-hex>");
  process.exit(2);
}
const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
const input = new Uint8Array(
  clean.match(/.{2}/g)!.map((b) => parseInt(b, 16)),
);
console.log(`Input: ${input.length} bytes`);

const deployment = loadDeployment();
console.log(`Calling ${deployment.contractAddress} on ${wsUrl()}`);

const account = accountFromMnemonic(requireMnemonic());
const { client, api } = await connect();

const destHex = deployment.contractAddress.startsWith("0x")
  ? deployment.contractAddress.slice(2)
  : deployment.contractAddress;
const destBytes = new Uint8Array(
  destHex.match(/.{2}/g)!.map((b) => parseInt(b, 16)),
);

const callArgs = {
  dest: FixedSizeBinary.fromBytes(destBytes),
  value: 0n,
  // Generous weight for the verify_player path; real measurement is S6 work.
  weight_limit: { ref_time: 500_000_000_000n, proof_size: 5_000_000n },
  storage_deposit_limit: 10_000_000_000_000n,
  data: Binary.fromBytes(input),
};

console.log("Submitting Revive.call with verify_player payload ...");
const result = await api.tx.Revive.call(callArgs).signAndSubmit(account.signer);

console.log("");
console.log("=== Submission result ===");
console.log(`block: ${result.block?.hash ?? "?"}`);
console.log(`ok: ${result.ok}`);
console.log(`events: ${result.events?.length ?? 0}`);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const stringifyBig = (v: any) => JSON.stringify(v, (_k, x) =>
  typeof x === "bigint" ? x.toString() + "n" : x, 2);

for (const event of result.events ?? []) {
  if (event.type === "Revive") {
    console.log(`  Revive.${event.value?.type}`);
  } else if (event.type === "System" && event.value?.type === "ExtrinsicFailed") {
    console.error(`ExtrinsicFailed:`, stringifyBig(event.value.value));
  } else if (event.type === "System" && event.value?.type === "ExtrinsicSuccess") {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const w = (event.value.value as any)?.dispatch_info?.weight;
    console.log(`  System.ExtrinsicSuccess (weight: ref_time=${w?.ref_time}, proof_size=${w?.proof_size})`);
  }
}

if (!result.ok) {
  console.error("Call failed — contract likely trapped.");
  await client.destroy();
  process.exit(1);
}

console.log("");
console.log("✓ Contract ran to completion (returned, didn't trap).");
console.log("  The 32-byte status blob isn't visible here; read it via state_call");
console.log("  ReviveApi_call if the pass/fail distinction is needed.");

await client.destroy();
