/**
 * Submit a verify_shuffle call to the deployed contract with a framed
 * payload generated by the `gen-shuffle` host tool.
 *
 *   npm run verify-shuffle -- 0x<framed-hex>
 *
 * The framed blob starts with selector 0x02, followed by player hellos,
 * the current deck, and the ShuffleMessage. See contract main.rs header
 * for the exact layout.
 *
 * We request a very generous weight limit so the chain doesn't cut the
 * call short — this is the S7 feasibility measurement. The actual weight
 * consumed is reported in ExtrinsicSuccess.dispatch_info.weight.
 */
import { Binary, FixedSizeBinary } from "polkadot-api";
import { loadDeployment, requireMnemonic, wsUrl } from "./env.js";
import { accountFromMnemonic } from "./signer.js";
import { connect } from "./client.js";

const hex = process.argv[2];
if (!hex) {
  console.error("usage: npm run verify-shuffle -- 0x<framed-hex>");
  process.exit(2);
}
const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
const input = new Uint8Array(
  clean.match(/.{2}/g)!.map((b) => parseInt(b, 16)),
);
console.log(`Input: ${input.length} bytes`);
console.log(`Selector: 0x${input[0]?.toString(16).padStart(2, "0")}`);

const deployment = loadDeployment();
console.log(`Calling ${deployment.contractAddress} on ${wsUrl()}`);

const account = accountFromMnemonic(requireMnemonic());
const { client, api } = await connect();

const destHex = deployment.contractAddress.startsWith("0x")
  ? deployment.contractAddress.slice(2)
  : deployment.contractAddress;
const destBytes = new Uint8Array(
  destHex.match(/.{2}/g)!.map((b) => parseInt(b, 16)),
);

const callArgs = {
  dest: FixedSizeBinary.fromBytes(destBytes),
  value: 0n,
  // S7: request the maximum weight we can — up to the full normal dispatch
  // budget (75% of 2s block = 1.5s). The chain will charge actual consumption.
  weight_limit: { ref_time: 1_200_000_000_000n, proof_size: 5_000_000n },
  storage_deposit_limit: 10_000_000_000_000n,
  data: Binary.fromBytes(input),
};

console.log("");
console.log("Submitting Revive.call with verify_shuffle payload ...");
console.log(`  weight_limit: ref_time=${callArgs.weight_limit.ref_time}, proof_size=${callArgs.weight_limit.proof_size}`);
console.log(`  data size: ${input.length} bytes`);
console.log("");

const result = await api.tx.Revive.call(callArgs).signAndSubmit(account.signer);

console.log("=== Submission result ===");
console.log(`block: ${result.block?.hash ?? "?"}`);
console.log(`ok: ${result.ok}`);
console.log(`events: ${result.events?.length ?? 0}`);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const stringifyBig = (v: any) => JSON.stringify(v, (_k, x) =>
  typeof x === "bigint" ? x.toString() + "n" : x, 2);

for (const event of result.events ?? []) {
  if (event.type === "Revive") {
    console.log(`  Revive.${event.value?.type}`);
  } else if (event.type === "System" && event.value?.type === "ExtrinsicFailed") {
    console.error(`  ExtrinsicFailed:`, stringifyBig(event.value.value));
  } else if (event.type === "System" && event.value?.type === "ExtrinsicSuccess") {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const w = (event.value.value as any)?.dispatch_info?.weight;
    console.log("");
    console.log("=== WEIGHT MEASUREMENT (S7) ===");
    console.log(`  ref_time:   ${w?.ref_time}`);
    console.log(`  proof_size: ${w?.proof_size}`);
    if (w?.ref_time) {
      const refTime = BigInt(w.ref_time);
      const blockBudget = 2_000_000_000_000n;
      const normalBudget = 1_500_000_000_000n;
      const pctBlock = Number((refTime * 10000n) / blockBudget) / 100;
      const pctNormal = Number((refTime * 10000n) / normalBudget) / 100;
      console.log(`  % of block:  ${pctBlock}%`);
      console.log(`  % of normal: ${pctNormal}%`);
    }
    console.log("");
  }
}

if (!result.ok) {
  console.error("Call failed — contract likely trapped or ran out of gas.");
  console.error("This may mean verify_shuffle exceeds the block weight limit.");
  await client.destroy();
  process.exit(1);
}

console.log("verify_shuffle ran to completion (ExtrinsicSuccess, no revert).");
console.log("Check the weight measurement above for the S7 feasibility verdict.");

await client.destroy();
